#!/usr/bin/env python
import sys, os

html_template = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{title}</title>
  <meta name="description" content="{title}">
  <link rel="stylesheet" href="css/styles.css">
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
  <script src="js/scripts.js"></script>
</head>
<body>
</body>
</html>"""

def make_html(**kwargs):
    print "Making index.html for site %s" % kwargs['title']
    with open("index.html", 'w') as f:
        f.write(html_template.format(**kwargs))

def make_full_path(filename):
    print "Making %s" % filename
    directory = os.path.dirname(filename)
    if not os.path.exists(directory):
        os.makedirs(directory)
    
    with open(filename, 'w') as f:
        f.write('')

def usage():
    print "makesite [site name]"

def main(argv):
    if len(argv)!=2:
        usage()
        return 1

    if "help" in argv[1]:
        usage()
        return 0

    try:
        make_html(title=argv[1])
        make_full_path("css/styles.css")
        make_full_path("js/scripts.css")
        print "Done"
    except Exception as e:
        print str(e)
        return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))

